### ISSUE TITLE
I want to change other huggingface local models.

### ISSUE THREAD

**Issue by haxx12113** [rhohndorf/Auto-Llama-cpp#1]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

1. If I want to change other huggingface local models, shall I modify this field? llm = Llama(model_path="ggml-vicuna-13b-4bit.bin", n_ctx=2048, embedding=True) But they have a lot of bin section is how to load: https://huggingface.co/chavinlo/gpt4-x-alpaca/tree/main
pytorch_model-00001-of-00006.bin
pytorch_model-00002-of-00006.bin
pytorch_model-00003-of-00006.bin
pytorch_model-00004-of-00006.bin
pytorch_model-00005-of-00006.bin
pytorch_model-00006-of-00006.bin
2. May I ask if I need to fill in my openai-key when I query the configuration file /.env.template with OPENAI_API_KEY=your-openai-api-key? I see that the code does not run Openai-key, shall I use it to access openai in later versions? Can I omit this parameter now?

**Comment by rhohndorf** [comment]
Hi, for models to work llama.cpp you need the model as one special ggml file. Please check here https://github.com/ggerganov/llama.cpp for more info. 

You don't need an OpenAI key as this is completely local. In fact OpenAI support probably does not work anymore after I was done. 

Just replace the model path with your model.
