### ISSUE TITLE
LLM call

### ISSUE THREAD

**Issue by zhanglei1172** [rhohndorf/Auto-Llama-cpp#15]
Hi, I noticed that when calling LLM in the code, only the first item in the messages list is passed as the prompt. Is this an error?
https://github.com/rhohndorf/Auto-Llama-cpp/blob/e2aa7c4adf20bde3badaa9ffe3ef160c8bc15de1/scripts/llm_utils.py#L8

**Comment by rhohndorf** [comment]
Ya i think so. When i hacked this together i really wasn't sure what the code does and just wanted to get a a first version out. After reading it more carefully, i'm pretty sure there's a bug in there.
