### ISSUE TITLE
Error message when calling scripts/main.py

### ISSUE THREAD

**Issue by maddes8cht** [rhohndorf/Auto-Llama-cpp#19]
### Duplicates

- [X] I have searched the existing issues

### Steps to reproduce 🕹

I pulled the git repository, edited my copy of .env to suit my needs, and even recreated a run.bat from the original AutoGPT project, adding the check_requirements.py script to the scripts (why was it actually removed?).
Using a conda environment with Python 3.10.10
Pip successfully installed all requirements

### Current behavior 😯

now calling 
``python scripts/main.py``
results in
```
Traceback (most recent call last):
  File "E:\LLama\Auto-Llama-cpp\scripts\main.py", line 3, in <module>
    import commands as cmd
  File "E:\LLama\Auto-Llama-cpp\scripts\commands.py", line 1, in <module>
    import browse
  File "E:\LLama\Auto-Llama-cpp\scripts\browse.py", line 4, in <module>
    from llm_utils import create_chat_completion
  File "E:\LLama\Auto-Llama-cpp\scripts\llm_utils.py", line 7
    def create_chat_completion(messages[0]["content"], model=None, temperature=cfg.temperature, max_tokens=0)->str:
                                       ^
SyntaxError: invalid syntax
```

What am i doing wrong?

### Expected behavior 🤔

It never executes as it should and doesn't seem to find my model.
Im not sure if that is the problem or if it's even earlier.

### Your prompt 📝

There is no  last_run_ai_settings.yaml, because it never executes.

What am i doing wrong?

**Comment by maddes8cht** [comment]
Turns out when i revert to commit e2aa7c4 from 17.04.2023 it starts working.
However, then I'm stuck  with the foreever swirrling `thinking` prompt...

**Comment by JavierPorron** [comment]
I modified the `create_chat_completition` funciton in file `llm_utils.py` to solve it:
``` python
def create_chat_completion(messages, model=None, temperature=cfg.temperature, max_tokens=0)->str:
    response = llm(messages[0]["content"], stop=["Q:", "### Human:"], echo=False, temperature=temperature, max_tokens=max_tokens)
    return response["choices"][0]["text"]
```
After that, in my case, I have to set the `TEMPERATURE` var in `.env` file.
Finally it shows to me the following error:
``` Bash
Traceback (most recent call last):
  File "C:\Users\venum\Documents\Github\Auto-Llama-cpp\scripts\main.py", line 331, in <module>
    assistant_reply = chat.chat_with_ai(
  File "C:\Users\venum\Documents\Github\Auto-Llama-cpp\scripts\chat.py", line 77, in chat_with_ai
    relevant_memory = permanent_memory.get_relevant(str(full_message_history[-5:]), 10)
  File "C:\Users\venum\Documents\Github\Auto-Llama-cpp\scripts\memory\local.py", line 105, in get_relevant
    scores = np.dot(self.data.embeddings, embedding)
  File "<__array_function__ internals>", line 180, in dot
ValueError: shapes (0,8192) and (5120,) not aligned: 8192 (dim 1) != 5120 (dim 0)
````

**Comment by rhohndorf** [comment]
If someone has a working solution with newest versions of llama-cpp-ypthon etc please create a pull request. Make sure everything works, as i can not test during the next week.

**Comment by rhohndorf** [comment]
Fixed
