### ISSUE TITLE
cublas implemetation?

### ISSUE THREAD

**Issue by yesbroc** [rhohndorf/Auto-Llama-cpp#29]
### Duplicates

- [X] I have searched the existing issues

### Summary 💡

for llama, there's a flag called --gpu-layers N, basically oflloads some layers to the gpu for processing

### Examples 🌈

![image](https://github.com/rhohndorf/Auto-Llama-cpp/assets/99485225/f7e651a1-81d7-4b11-b4f0-90967d98d7cd)
from ooba

### Motivation 🔦

since cpu is super slow, gpu would be nice

**Comment by rhohndorf** [comment]
You have to set some environment variables before llama-cpp-python installation so that it get compiled with cublas support. Follow the instructions here: https://pypi.org/project/llama-cpp-python/
